{
 "title": "System",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "ds", "label": "Server", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$col",
     "expr": "node_load1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "CPU",
     "measurement": "system",
     "select": [
      [
       { "params": [ "load1" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       },
       { "params": [ "load1" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_interface.$col",
     "expr": "irate(node_network_receive_bytes_total{device!~\"lo.*\"}[$__interval])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{device}} - Receive",
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "bytes_sent" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "bytes_recv" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "$tag_interface.$col",
     "expr": "irate(node_network_transmit_bytes_total{device!~\"lo.*\"}[$__interval])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{device}} - Transmit",
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "bytes_sent" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "bytes_recv" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "$tag_interface.$col",
     "expr": "irate(node_network_receive_errs_total{device!~\"lo.*\"}[$__interval])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{device}} - Errors",
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "bytes_sent" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "bytes_recv" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "$tag_interface.$col",
     "expr": "irate(node_network_receive_drop_total{device!~\"lo.*\"}[$__interval])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{device}} - Dropped",
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "bytes_sent" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "bytes_recv" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk Temperatures",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "$tag_device [$tag_serial_no]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "serial_no" ], "type": "tag" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "smart_device",
     "query": "SELECT mean(\"temp_c\") FROM \"smart_device\" WHERE $timeFilter GROUP BY time($__interval), \"serial_no\" fill(null)",
     "select": [
      [
       { "params": [ "temp_c" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "3" ], "type": "moving_average" },
       { "params": [ "temp" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "cpu" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT non_negative_difference(last(\"time_iowait\")) AS \"iowait\", non_negative_difference(last(\"time_nice\")) AS \"nice\", non_negative_difference(last(\"time_system\")) AS \"system\", non_negative_difference(last(\"time_user\")) AS \"user\", non_negative_difference(last(\"time_iowait\")) AS \"iowait\" FROM \"cpu\" WHERE $timeFilter GROUP BY time($__interval), \"host\", \"cpu\" fill(null)",
     "select": [
      [
       { "params": [ "usage_nice" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "nice" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_iowait" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "iowait" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_irq" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "irq" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "system" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "user" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_softirq" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "softirq" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_steal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "steal" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_guest" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "guest" ], "type": "alias" }
      ],
      [
       { "params": [ "usage_guest_nice" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "guest_nice" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "$measurement",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu_temp",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk Reads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "expr": "irate(node_devstat_bytes_total{type=\"read\",device!~\"pass.*\"}[$__interval])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{device}}",
     "measurement": "diskio",
     "query": "SELECT non_negative_derivative(last(\"read_bytes\"), $__interval) AS \"read_bytes\" FROM \"diskio\" WHERE (\"name\" !~ /^pass/) AND $timeFilter GROUP BY time($__interval), \"name\" fill(null)",
     "select": [
      [
       { "params": [ "read_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "read_bytes" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "!~", "value": "/^pass/" }
     ]
    }
   ]
  },
  {
   "title": "ZPool Status",
   "type": "table",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 7 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "pool" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "zpool_status",
     "select": [
      [
       { "params": [ "state" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "state" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_device.$col [$tag_serial_no]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "serial_no" ], "type": "tag" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "smart_device",
     "query": "SELECT non_negative_derivative(mean(\"read_error_rate\"), 1s) AS \"read_error_rate\", non_negative_derivative(mean(\"seek_error_rate\"), 1s) AS \"seek_error_rate\", non_negative_derivative(mean(\"udma_crc_errors\"), 1s) AS \"udma_crc_errors\" FROM \"smart_device\" WHERE $timeFilter GROUP BY time($__interval), \"serial_no\", \"device\", \"host\" fill(null)",
     "select": [
      [
       { "params": [ "read_error_rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "read_error_rate" ], "type": "alias" }
      ],
      [
       { "params": [ "seek_error_rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "seek_error_rate" ], "type": "alias" }
      ],
      [
       { "params": [ "udma_crc_errors" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "udma_crc_errors" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "used" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk Writes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "expr": "irate(node_devstat_bytes_total{type=\"write\",device!~\"pass.*\"}[$__interval])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{device}}",
     "measurement": "diskio",
     "query": "SELECT non_negative_derivative(last(\"write_bytes\"), 10s) AS \"write_bytes\" FROM \"diskio\" WHERE (\"name\" !~ /^pass/) AND $timeFilter GROUP BY time($__interval), \"name\" fill(null)",
     "select": [
      [
       { "params": [ "write_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "write_bytes" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk Free Space (system)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_device",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "free" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "free" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "zroot" },
      { "condition": "OR", "key": "device", "operator": "=", "value": "support" }
     ]
    }
   ]
  },
  {
   "title": "Disk Free Space (data)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 14 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_device",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "free" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "free" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "data" },
      { "condition": "OR", "key": "device", "operator": "=", "value": "/data/local/Downloads" }
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "max(node_cpu_temperature_celsius)",
     "legendFormat": "CPU"
    }
   ]
  }
 ]
}