apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  grafana_dashboard: "true"
configMapGenerator:
  # NOTE single dashboard per ConfigMap
  - name: freebsd-dashboard
    behavior: create
    files:
      - freebsd.json=dashboards/freebsd.json
  - name: mikee-pc-dashboard
    behavior: create
    files:
      - mikee-pc.json=dashboards/mikee-pc.json
