{
 "title": "Mikee-PC",
 "tags": [ "windows" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# AMD Ryzen 9 3900X ~ 4250 Mhz / NVIDIA GeForce GTX 1070"
   },
   "targets": [
    {
     "expr": "ohm_cpu_celsius{hardware=\"AMD Ryzen 9 3900X\"}"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ohm_cpu_load_percent{sensor=\"CPU Total\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "CPU Power",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ohm_cpu_watts{sensor=\"Package Power\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "CPU Temperature",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ohm_cpu_celsius{sensor=\"Core (Tctl/Tdie)\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "GPU Core Load",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ohm_gpunvidia_load_percent{sensor=\"GPU Core\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "GPU Core Power",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "ohm_gpunvidia_watts", "legendFormat": "{{sensor}}" }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "ohm_gpunvidia_celsius", "legendFormat": "{{sensor}}" }
   ]
  },
  {
   "title": "Radiator Outlet",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "esp_celsius{sensor=\"Water Outlet\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "RPM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 14, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ohm_superio_revolutions_per_minute{sensor=\"Fan #1\"}",
     "legendFormat": "Water Pump (CPU)"
    },
    {
     "expr": "ohm_superio_revolutions_per_minute{sensor=\"Fan #5\"}",
     "legendFormat": "Case Front (CPU_OPT)"
    },
    {
     "expr": "ohm_superio_revolutions_per_minute{sensor=\"Fan #3\"}",
     "legendFormat": "Case Rear (System 2)"
    },
    {
     "expr": "ohm_superio_revolutions_per_minute{sensor=\"Fan #2\"}",
     "legendFormat": "PSU (System 1)"
    },
    {
     "expr": "esp_rpm{hardware=\"Radiator\"}",
     "legendFormat": "{{hardware}} {{sensor}}"
    }
   ]
  },
  {
   "title": "Used Space",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ohm_hdd_load_percent{sensor=\"Used Space\",hardware=\"XPG GAMMIX S11 Pro\"}",
     "legendFormat": "System (C:)"
    },
    {
     "expr": "ohm_hdd_load_percent{sensor=\"Used Space\",hardware=\"Msft Storage Space\"}",
     "legendFormat": "Data (D:)"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "ohm_cpu_load_percent{sensor=\"CPU Total\"}",
     "legendFormat": "{{sensor}}"
    },
    {
     "expr": "ohm_ram_load_percent{sensor=\"Memory\"}",
     "legendFormat": "System {{sensor}}"
    },
    {
     "expr": "ohm_gpunvidia_load_percent{sensor=~\"GPU Core|GPU Memory\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "ohm_ram_bytes{sensor=~\"Memory Used\"}",
     "legendFormat": "{{sensor}}"
    },
    {
     "expr": "ohm_ram_bytes{sensor=~\"Memory Available\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "°C" }
   ],
   "targets": [
    {
     "expr": "max_over_time(ohm_cpu_celsius{sensor=\"Core (Tctl/Tdie)\"}[$__interval])",
     "legendFormat": "{{hardware}} "
    },
    {
     "expr": "max_over_time(ohm_gpunvidia_celsius[$__interval])",
     "legendFormat": "{{hardware}}"
    },
    {
     "expr": "max_over_time(ohm_superio_celsius{sensor=\"Temperature #5\"}[$__interval])",
     "legendFormat": "VRM MOS"
    },
    {
     "expr": "max_over_time(ohm_superio_celsius{sensor=\"Temperature #6\"}[$__interval])",
     "legendFormat": "Chipset"
    },
    {
     "expr": "max_over_time(ohm_hdd_celsius[$__interval])",
     "legendFormat": "{{hardware}}"
    },
    {
     "expr": "max_over_time(esp_celsius{sensor!=\"ESP32\",component=\"radiator\"}[$__interval])",
     "legendFormat": "{{hardware}} - {{sensor}}"
    },
    {
     "expr": "min_over_time(esp_celsius{sensor=\"Water Inlet\",component=\"radiator\"}[$__interval]) - ignoring(sensor,address) max_over_time(esp_celsius{sensor=\"Water Outlet\",component=\"radiator\"}[$__interval])",
     "legendFormat": "{{hardware}} - Delta"
    },
    {
     "expr": "min_over_time(esp_celsius{sensor=\"Water Outlet\",component=\"radiator\"}[$__interval]) - ignoring(sensor,address) max_over_time(esp_celsius{sensor=\"Ambient\",component=\"radiator\"}[$__interval])",
     "legendFormat": "{{hardware}} - Above"
    }
   ]
  },
  {
   "type": "table-old",
   "gridPos": { "h": 10, "w": 5, "x": 14, "y": 12 },
   "targets": [
    {
     "expr": "max_over_time(ohm_cpu_celsius{sensor=\"Core (Tctl/Tdie)\"}[$__interval])",
     "legendFormat": "{{hardware}} - {{sensor}}"
    },
    {
     "expr": "max_over_time(ohm_gpunvidia_celsius[$__interval])",
     "legendFormat": "{{hardware}} - {{sensor}}"
    },
    {
     "expr": "max_over_time(ohm_superio_celsius{sensor=\"Temperature #5\"}[$__interval])",
     "legendFormat": "VRM MOS"
    },
    {
     "expr": "max_over_time(ohm_superio_celsius{sensor=\"Temperature #6\"}[$__interval])",
     "legendFormat": "Chipset"
    },
    {
     "expr": "max_over_time(ohm_hdd_celsius[$__interval])",
     "legendFormat": "{{hardware}}"
    },
    {
     "expr": "max_over_time(esp_celsius[$__interval])",
     "legendFormat": "{{hardware}} - {{sensor}}"
    },
    {
     "expr": "min_over_time(esp_celsius{sensor=\"Water Inlet\"}[$__interval]) - ignoring(sensor,address) max_over_time(esp_celsius{sensor=\"Water Outlet\"}[$__interval])",
     "legendFormat": "{{hardware}} - Delta"
    },
    {
     "expr": "min_over_time(esp_celsius{sensor=\"Water Outlet\"}[$__interval]) - ignoring(sensor,address) max_over_time(esp_celsius{sensor=\"Ambient\"}[$__interval])",
     "legendFormat": "{{hardware}} - Above"
    }
   ]
  },
  {
   "title": "Power",
   "type": "graph",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short", "label": "W" }
   ],
   "targets": [
    {
     "expr": "ohm_cpu_watts{sensor=\"Package Power\"}",
     "legendFormat": "{{hardware}} - {{sensor}}"
    },
    { "expr": "ohm_gpunvidia_watts", "legendFormat": "{{hardware}} - {{sensor}}" }
   ]
  },
  {
   "title": "Voltage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short", "label": "V" }
   ],
   "targets": [
    {
     "expr": "ohm_cpu_volts{sensor=~\".*TFN.*\"}",
     "legendFormat": "{{hardware}} - {{sensor}}"
    },
    {
     "expr": "ohm_superio_volts{sensor=\"Vcore\"}",
     "legendFormat": "{{sensor}}"
    },
    {
     "expr": "ohm_superio_volts{sensor=\"Voltage #5\"}",
     "legendFormat": "Vcore SoC"
    }
   ]
  }
 ]
}